name: todo_list_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3
  riverpod_annotation: ^2.6.1

  # Logging
  stack_trace: ^1.11.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  form_builder_validators: ^11.2.0
  pinput: ^5.0.1
  go_router: ^16.2.0
  fpdart: ^1.1.1
  fast_immutable_collections: ^11.0.4
  uuid: ^4.5.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Logging
  logger: ^2.6.1

  # generator
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  dart_mappable_builder: ^4.2.3
  
  go_router_builder: ^2.7.1
  build_verify: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
          weight: 900
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Thin.ttf
          weight: 100